spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Root@123
    url: jdbc:mysql://localhost:3306/springbootcrudapi
    username: root
  jpa:
      hibernate:
                ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
       
  main:
    allow-circular-references: true
jwt.secret: javainuse12345678901234567890123456789012345678901234567890123456789012345678901234567890

